"""create cargo conversion rules table

Revision ID: 6e652feee51c
Revises: e54c2399c29d
Create Date: 2026-07-20 16:48:10.990091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e652feee51c'
down_revision: Union[str, Sequence[str], None] = 'e54c2399c29d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo_conversion_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity_id', sa.UUID(), nullable=True),
    sa.Column('source_unit', sa.String(length=50), nullable=False),
    sa.Column('target_unit', sa.String(length=50), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cargo_conversion_rules')
    # ### end Alembic commands ###
