"""add_projection_fields_to_cargo_flows

Revision ID: e54c2399c29d
Revises: 56243f54b687
Create Date: 2026-07-18 21:49:10.975677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54c2399c29d'
down_revision: Union[str, Sequence[str], None] = '56243f54b687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo_flows', sa.Column('start_year', sa.Integer(), nullable=False))
    op.add_column('cargo_flows', sa.Column('growth_rate', sa.Float(), nullable=False))
    op.add_column('cargo_flows', sa.Column('maximum_demand', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cargo_flows', 'maximum_demand')
    op.drop_column('cargo_flows', 'growth_rate')
    op.drop_column('cargo_flows', 'start_year')
    # ### end Alembic commands ###
